import collections

Color = collections.namedtuple("Color", ("name", "rgb"))
height = 8
width = 10
colors = [
    Color(name="Wine Red", rgb="#A35A6E"),
    Color(name="Rose Red", rgb="#F3595F"),
    Color(name="Vivid Red", rgb="#F4565F"),
    Color(name="Vivid Pink", rgb="#FE62E5"),
    Color(name="Cosmos", rgb="#F1AF8D"),
    Color(name="Pale Pink", rgb="#F3B9CC"),
    Color(name="Deep Red", rgb="#F15965"),
    Color(name="Scarlet", rgb="#F66664"),
    Color(name="Vermilion", rgb="#F97E54"),
    Color(name="Coral Pink", rgb="#F97869"),
    Color(name="Pastel Pink", rgb="#FED4F1"),
    Color(name="Peach", rgb="#F7CAAC"),
    Color(name="Terra Cotta", rgb="#D79946"),
    Color(name="French Vermilion", rgb="#F97849"),
    Color(name="Orange", rgb="#E28451"),
    Color(name="Marigold", rgb="#DB7545"),
    Color(name="Salmon Pink", rgb="#FEF2B6"),
    Color(name="Fruit Pink", rgb="#FDE4AF"),
    Color(name="Barely Beige", rgb="#FEF6B7"),
    Color(name="Dark Yellow", rgb="#DEAF43"),
    Color(name="Melon Yellow", rgb="#F2BF42"),
    Color(name="Lemon Yellow", rgb="#FEE138"),
    Color(name="Cream", rgb="#FDE782"),
    Color(name="Pastel Yellow", rgb="#FEE83B"),
    Color(name="Olive Green", rgb="#C3B14A"),
    Color(name="Bronze Green", rgb="#6F7C40"),
    Color(name="Deep Olive Green", rgb="#386A48"),
    Color(name="Fresh Green", rgb="#FDDC3B"),
    Color(name="Vivid Green", rgb="#42BC9C"),
    Color(name="Grass Green", rgb="#6EC97D"),
    Color(name="Yellow Green", rgb="#B9E051"),
    Color(name="Pastel Green", rgb="#FFFE97"),
    Color(name="Forest Green", rgb="#3C7C8D"),
    Color(name="Turquoise Green", rgb="#386D58"),
    Color(name="Mint Green", rgb="#9BE39A"),
    Color(name="Turquoise Green Light", rgb="#367686"),
    Color(name="Mint Green Light", rgb="#51CAC9"),
    Color(name="Pale Green", rgb="#70C76E"),
    Color(name="Peacock Green", rgb="#48BFC3"),
    Color(name="Marine Blue", rgb="#2B4F74"),
    Color(name="Cerulean Blue", rgb="#CECFD0"),
    Color(name="Ice Blue", rgb="#4AC1E5"),
    Color(name="Pastel Blue", rgb="#4FC9F5"),
    Color(name="Turquoise Blue", rgb="#73DBF2"),
    Color(name="Prussian Blue", rgb="#283E84"),
    Color(name="Royal Blue", rgb="#366ED9"),
    Color(name="Ultra Marine", rgb="#7E76F8"),
    Color(name="Dark Blue Light", rgb="#B1B9FE"),
    Color(name="Sky Blue", rgb="#C1EBFF"),
    Color(name="Pale Blue", rgb="#EEEBFE"),
    Color(name="Deep Violet", rgb="#563CB6"),
    Color(name="Pastel Violet", rgb="#FED5EE"),
    Color(name="Vivid Purple", rgb="#CF54DB"),
    Color(name="Pale Purple", rgb="#FAC0D7"),
    Color(name="Natural Oak", rgb="#A66E69"),
    Color(name="Brick Brown", rgb="#CEA199"),
    Color(name="Rose Biege", rgb="#CD9668"),
    Color(name="Bronze", rgb="#7B675C"),
    Color(name="Yellow Ochre", rgb="#B0894A"),
    Color(name="Brown Grey", rgb="#C4A152"),
    Color(name="Sand", rgb="#E0B57A"),
    Color(name="Black", rgb="#40434A"),
    Color(name="Skin White", rgb="#FCFCEE"),
    Color(name="Pale Cherry Pink", rgb="#FEFBE2"),
    Color(name="Light Pink", rgb="#FFFDFE"),
    Color(name="Light Orange", rgb="#F5C17C"),
    Color(name="Pale Baby Blue", rgb="#C8EEFF"),
    Color(name="Pale Lilac", rgb="#FFF7FE"),
    Color(name="Green Bice", rgb="#EBFAA6"),
    Color(name="Spectrum Green", rgb="#D5FBFC"),
    Color(name="Phthalo Blue", rgb="#79BBFF"),
    Color(name="Blue Grey 3", rgb="#96BDC7"),
    Color(name="Blue Grey 5", rgb="#628D98"),
    Color(name="Blue Grey 7", rgb="#406067"),
    Color(name="Cool Grey 9", rgb="#444F4F"),
    Color(name="Green Grey 3 ", rgb="#CDDFCF"),
    Color(name="Green Grey 5", rgb="#90A994"),
    Color(name="Warm Grey 3", rgb="#D2D5C5"),
    Color(name="Warm Grey 6", rgb="#7D7E70"),
    Color(name="Warm Grey 9", rgb="#535446"),
]
assert len(colors) == height * width
